USE [master]
GO

/****** Object:  Database [DEV_MUSHROOM]    Script Date: 18/11/2020 09:08:23 ******/
CREATE DATABASE [DEV_MUSHROOM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DEV_MUSHROOM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DEV_MUSHROOM.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DEV_MUSHROOM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DEV_MUSHROOM_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DEV_MUSHROOM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DEV_MUSHROOM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET ARITHABORT OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DEV_MUSHROOM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DEV_MUSHROOM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DEV_MUSHROOM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DEV_MUSHROOM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DEV_MUSHROOM] SET  MULTI_USER 
GO

ALTER DATABASE [DEV_MUSHROOM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DEV_MUSHROOM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DEV_MUSHROOM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DEV_MUSHROOM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DEV_MUSHROOM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DEV_MUSHROOM] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DEV_MUSHROOM] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DEV_MUSHROOM] SET  READ_WRITE 
GO


